substitutions:
  device_name: car-tracker
  friendly_name: Car Tracker
  device_description: NEO-8M GPS tracker

packages:
  device: !include devices/esp32_s3_supermini.yaml

api:
  encryption:
    key: "zAp1dOC8x2maPwT3fvGHx0/F2zDGDWXoP/30gFdXMXA="

uart:
  - id: gps_uart
    tx_pin: GPIO43
    rx_pin: GPIO44
    baud_rate: 9600

gps:
  id: gps_module
  uart_id: gps_uart
  latitude:
    name: "GPS Latitude"
    id: gps_lat
  longitude:
    name: "GPS Longitude"
    id: gps_lon
  speed:
    name: "GPS Speed"
    id: gps_speed
  altitude:
    name: "GPS Altitude"
    id: gps_alt
  course:
    name: "GPS Course"
    id: gps_course

web_server:
  auth:
    username: admin
    password: "web_password_here"
